-- Create clients table if not exists (Previous Step)
create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_id text unique not null,
  official_name text not null,
  address text,
  gst text,
  cin text,
  contact_email text,
  sender_email text,              -- Email address to send invoices from for this client
  recurring_amount numeric,
  billing_day integer default 7,  -- Day of month to send invoice (1-31)
  -- Custom invoice template fields
  invoice_template text,          -- Template ID (e.g., 'gcx' for GCX-specific format)
  place_of_supply text,           -- Place of supply for GST (e.g., 'Maharashtra')
  pan_no text                     -- PAN number for specific clients
);

-- UPDATE FOR EXISTING TABLES (run if table already exists):
-- alter table public.clients add column if not exists invoice_template text;
-- alter table public.clients add column if not exists place_of_supply text;
-- alter table public.clients add column if not exists pan_no text;
--
-- To set GCX custom invoice template:
-- update public.clients set invoice_template = 'gcx', place_of_supply = 'Maharashtra', pan_no = 'AFZPS5689F' where client_id = 'gcx';

-- Enable RLS for clients
alter table public.clients enable row level security;

-- Policy to allow all access to authenticated users (Previous Step)
drop policy if exists "Enable all access for authenticated users" on public.clients;
create policy "Enable all access for authenticated users" on public.clients
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');


-- ==========================================
-- EMPLOYEES TABLE SETUP
-- ==========================================

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  employee_id text unique not null,
  name text not null,
  salary numeric not null,
  employment_type text check (employment_type in ('Regular', 'Contractual')) not null,
  salary_date date,
  loan_amount numeric default 0,
  loan_deducted numeric default 0,
  tax_deduction numeric default 0
);

-- UPDATE FOR EXISTING TABLES:
-- If you already created the table, run this:
-- alter table public.employees add column if not exists tax_deduction numeric default 0;

-- Enable RLS for employees
alter table public.employees enable row level security;

-- Policy to allow all access to authenticated users for employees
drop policy if exists "Enable all access for authenticated users" on public.employees;
create policy "Enable all access for authenticated users" on public.employees
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- PROJECTS TABLE
create table if not exists public.projects (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_name text not null,
  project_name text not null,
  amount numeric not null,
  due_date date not null,
  status text default 'Pending',
  sender_email text              -- Email address to send invoice from for this project
);

-- RLS for Projects
alter table public.projects enable row level security;

drop policy if exists "Enable all access for now" on public.projects;
create policy "Enable all access for now"
on public.projects
for all
using (true)
with check (true);

-- EXPENSES TABLE
create table if not exists public.expenses (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  amount numeric not null,
  date date not null,
  category text default 'General',
  invoice_no text,
  payment_method text
);

-- UPDATE FOR EXISTING TABLES (run if table already exists):
-- ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS category text DEFAULT 'General';
-- ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS invoice_no text;
-- ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS payment_method text;

-- RLS for Expenses
alter table public.expenses enable row level security;

drop policy if exists "Enable all access for now" on public.expenses;
create policy "Enable all access for now"
on public.expenses
for all
using (true)
with check (true);

-- BILLS TABLE
create table if not exists public.bills (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  vendor_name text not null,
  description text,
  amount numeric not null,
  date date not null,
  file_path text,               -- Path in Supabase Storage (for uploaded files)
  file_url text,                -- Public URL or Google Drive link
  upload_type text default 'file' check (upload_type in ('file', 'link'))
);

-- RLS for Bills
alter table public.bills enable row level security;

drop policy if exists "Enable all access for now" on public.bills;
create policy "Enable all access for now"
on public.bills
for all
using (true)
with check (true);

-- ==========================================
-- INVOICE LOGS TABLE (for tracking sent invoices)
-- ==========================================

create table if not exists public.invoice_logs (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_id text not null,
  client_name text not null,
  client_email text not null,
  invoice_number text not null,
  invoice_date timestamp with time zone not null,
  amount numeric not null,
  invoice_type text check (invoice_type in ('recurring', 'project')) not null,
  email_id text, -- Resend email ID for tracking
  status text default 'sent' check (status in ('sent', 'delivered', 'failed', 'opened'))
);

-- RLS for Invoice Logs
alter table public.invoice_logs enable row level security;

drop policy if exists "Enable all access for authenticated users" on public.invoice_logs;
create policy "Enable all access for authenticated users" on public.invoice_logs
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Index for faster lookups by date and client
create index if not exists idx_invoice_logs_date on public.invoice_logs(invoice_date);
create index if not exists idx_invoice_logs_client on public.invoice_logs(client_id);

-- ==========================================
-- INVOICE BATCH LOGS (for scheduled batch executions)
-- ==========================================

create table if not exists public.invoice_batch_logs (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  execution_date timestamp with time zone not null,
  month text not null,
  total_clients integer not null,
  successful integer default 0,
  failed integer default 0,
  details jsonb
);

-- RLS for Invoice Batch Logs
alter table public.invoice_batch_logs enable row level security;

drop policy if exists "Enable all access for authenticated users" on public.invoice_batch_logs;
create policy "Enable all access for authenticated users" on public.invoice_batch_logs
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- ==========================================
-- PG_CRON SETUP FOR MONTHLY INVOICE EMAILS
-- ==========================================

-- Enable pg_cron extension (run as superuser in Supabase Dashboard SQL Editor)
-- create extension if not exists pg_cron;

-- Schedule monthly invoice emails on the 1st of each month at 9:00 AM IST (3:30 AM UTC)
-- NOTE: Run this in Supabase Dashboard SQL Editor after enabling pg_cron
/*
select cron.schedule(
  'monthly-invoice-emails',
  '30 3 1 * *', -- At 3:30 AM UTC on the 1st of every month
  $$
  select
    net.http_post(
      url:='https://qitojxxbqsgypbavkkch.supabase.co/functions/v1/scheduled-invoices',
      headers:='{"Content-Type": "application/json", "Authorization": "Bearer YOUR_SERVICE_ROLE_KEY"}'::jsonb,
      body:='{}'::jsonb
    ) as request_id;
  $$
);
*/

-- To view scheduled jobs:
-- select * from cron.job;

-- To unschedule:
-- select cron.unschedule('monthly-invoice-emails');

-- ==========================================
-- PENDING INVOICES TABLE (for n8n workflow)
-- ==========================================
-- This table acts as a queue for invoices to be sent via n8n

create table if not exists public.pending_invoices (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_id text not null,
  client_name text not null,
  client_email text not null,
  sender_email text,                -- Email address to send the invoice from
  invoice_number text not null,
  invoice_date date not null,
  amount numeric not null,
  invoice_type text check (invoice_type in ('recurring', 'project')) not null,
  project_name text,                -- For project invoices
  file_path text not null,          -- Path in Supabase Storage (e.g., 'invoices/INV_001.pdf')
  file_url text not null,           -- Public URL to the PDF
  status text default 'pending' check (status in ('pending', 'sent', 'failed')),
  sent_at timestamp with time zone,
  error_message text
);

-- RLS for Pending Invoices
alter table public.pending_invoices enable row level security;

drop policy if exists "Enable all access for authenticated users" on public.pending_invoices;
create policy "Enable all access for authenticated users" on public.pending_invoices
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Index for n8n to quickly find pending invoices
create index if not exists idx_pending_invoices_status on public.pending_invoices(status);

-- ==========================================
-- SUPABASE STORAGE BUCKET SETUP
-- ==========================================
-- Run this in Supabase Dashboard > Storage > New Bucket
-- Bucket name: invoices
-- Public: Yes (for easy URL access)
--
-- Or run via SQL:
-- insert into storage.buckets (id, name, public) values ('invoices', 'invoices', true);
--
-- Storage policy (run in SQL Editor):
-- create policy "Allow authenticated uploads" on storage.objects
--   for insert to authenticated with check (bucket_id = 'invoices');
-- create policy "Allow public read" on storage.objects
--   for select using (bucket_id = 'invoices');

-- ==========================================
-- DOT KNOWLEDGE BASE (for AI Chatbot RAG)
-- ==========================================

-- Enable vector extension (run this first)
-- create extension if not exists vector;

-- Knowledge base table for storing document chunks with embeddings
create table if not exists public.dot_knowledge_base (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  embedding vector(1536),  -- OpenAI text-embedding-3-small uses 1536 dimensions
  metadata jsonb
);

-- RLS for knowledge base
alter table public.dot_knowledge_base enable row level security;

drop policy if exists "Enable read access for all users" on public.dot_knowledge_base;
create policy "Enable read access for all users" on public.dot_knowledge_base
  for select using (true);

drop policy if exists "Enable insert for service role" on public.dot_knowledge_base;
create policy "Enable insert for service role" on public.dot_knowledge_base
  for insert with check (true);

-- Index for faster vector similarity search
create index if not exists dot_knowledge_base_embedding_idx
  on public.dot_knowledge_base
  using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

-- Function for vector similarity search (used by Edge Function)
create or replace function match_documents(
  query_embedding vector(1536),
  match_threshold float default 0.5,
  match_count int default 5
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    dot_knowledge_base.id,
    dot_knowledge_base.content,
    dot_knowledge_base.metadata,
    1 - (dot_knowledge_base.embedding <=> query_embedding) as similarity
  from dot_knowledge_base
  where 1 - (dot_knowledge_base.embedding <=> query_embedding) > match_threshold
  order by dot_knowledge_base.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- ==========================================
-- EXPERT CONSULTATIONS TABLE
-- ==========================================
-- Stores expert consultation requests from clients

create table if not exists public.consultation_requests (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users(id),
  user_email text not null,
  expert_name text not null,
  issue_title text not null,
  urgency text check (urgency in ('low', 'medium', 'high')) not null,
  phone_number text,
  description text not null,
  status text default 'pending' check (status in ('pending', 'in_progress', 'resolved', 'closed')),
  resolved_at timestamp with time zone,
  notes text
);

-- RLS for Expert Consultations
alter table public.consultation_requests enable row level security;

-- Policy: Users can insert their own consultations
drop policy if exists "Users can insert own consultations" on public.consultation_requests;
create policy "Users can insert own consultations" on public.consultation_requests
  for insert with check (auth.uid() = user_id or user_id is null);

-- Policy: Users can view their own consultations
drop policy if exists "Users can view own consultations" on public.consultation_requests;
create policy "Users can view own consultations" on public.consultation_requests
  for select using (auth.uid() = user_id or auth.role() = 'authenticated');

-- Policy: Admins can update consultations (for status changes)
drop policy if exists "Admins can update consultations" on public.consultation_requests;
create policy "Admins can update consultations" on public.consultation_requests
  for update using (auth.role() = 'authenticated');

-- Index for faster lookups
create index if not exists idx_consultation_requests_status on public.consultation_requests(status);
create index if not exists idx_consultation_requests_expert on public.consultation_requests(expert_name);
create index if not exists idx_consultation_requests_urgency on public.consultation_requests(urgency);
