-- Test Compliance Data for All Categories
-- Run this in Supabase SQL Editor to add test compliance items

-- First, let's check if compliance_library table exists and its structure
-- If it doesn't exist, create it:
CREATE TABLE IF NOT EXISTS public.compliance_library (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  rule_name text not null,
  license_type text not null,
  service_scope text default 'Common',
  condition_category text default 'General',
  frequency text,
  base_severity integer default 5
);

-- Enable RLS
ALTER TABLE public.compliance_library ENABLE ROW LEVEL SECURITY;

-- Policy for read access
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.compliance_library;
CREATE POLICY "Enable read access for authenticated users" ON public.compliance_library
  FOR SELECT USING (auth.role() = 'authenticated');

-- Insert Test Compliance Items for UL License Type
-- GENERAL CATEGORY (5 items)
INSERT INTO public.compliance_library (rule_name, license_type, service_scope, condition_category, frequency, base_severity) VALUES
('Submit Annual License Fee', 'UL', 'Common', 'General', 'Annual', 8),
('Update Company Registration Details', 'UL', 'Common', 'General', 'Annual', 5),
('Submit Quarterly Activity Report', 'UL', 'Common', 'General', 'Quarterly', 6),
('Maintain Complaint Redressal Records', 'UL', 'Common', 'General', 'Monthly', 4),
('Submit Change in Shareholding Pattern', 'UL', 'Common', 'General', 'Quarterly', 7);

-- FINANCIAL CATEGORY (5 items)
INSERT INTO public.compliance_library (rule_name, license_type, service_scope, condition_category, frequency, base_severity) VALUES
('Submit Annual Revenue Statement', 'UL', 'Common', 'Financial', 'Annual', 9),
('Pay License Fee Based on AGR', 'UL', 'Common', 'Financial', 'Quarterly', 10),
('Submit Bank Guarantee Renewal', 'UL', 'Common', 'Financial', 'Annual', 8),
('File GST Returns for Telecom Services', 'UL', 'Common', 'Financial', 'Monthly', 7),
('Submit Audited Financial Statements', 'UL', 'Common', 'Financial', 'Annual', 8);

-- TECHNICAL CATEGORY (5 items)
INSERT INTO public.compliance_library (rule_name, license_type, service_scope, condition_category, frequency, base_severity) VALUES
('Submit Network Capacity Report', 'UL', 'Common', 'Technical', 'Quarterly', 6),
('Maintain QoS Parameters', 'UL', 'Common', 'Technical', 'Monthly', 7),
('Submit Equipment Type Approval Report', 'UL', 'Common', 'Technical', 'Annual', 5),
('Update Network Topology Documentation', 'UL', 'Common', 'Technical', 'Quarterly', 4),
('Submit Interconnection Agreement Updates', 'UL', 'Common', 'Technical', 'Annual', 6);

-- SECURITY CATEGORY (5 items)
INSERT INTO public.compliance_library (rule_name, license_type, service_scope, condition_category, frequency, base_severity) VALUES
('Submit Security Audit Report', 'UL', 'Common', 'Security', 'Annual', 9),
('Update Lawful Interception System', 'UL', 'Common', 'Security', 'Quarterly', 10),
('Submit CAF Verification Compliance', 'UL', 'Common', 'Security', 'Monthly', 8),
('Maintain Call Data Records (CDR)', 'UL', 'Common', 'Security', 'Monthly', 9),
('Submit Cybersecurity Incident Report', 'UL', 'Common', 'Security', 'Quarterly', 7);

-- OPERATING CATEGORY (5 items)
INSERT INTO public.compliance_library (rule_name, license_type, service_scope, condition_category, frequency, base_severity) VALUES
('Submit Subscriber Base Report', 'UL', 'Common', 'Operating', 'Monthly', 5),
('Update Points of Interconnection (POI)', 'UL', 'Common', 'Operating', 'Quarterly', 6),
('Submit Tariff Plan Filing', 'UL', 'Common', 'Operating', 'Monthly', 4),
('Maintain Customer Grievance Portal', 'UL', 'Common', 'Operating', 'Monthly', 5),
('Submit MNP Compliance Report', 'UL', 'Common', 'Operating', 'Quarterly', 6);

-- Also add items for UL-VNO license type
INSERT INTO public.compliance_library (rule_name, license_type, service_scope, condition_category, frequency, base_severity) VALUES
-- General
('Submit Annual License Fee (VNO)', 'UL-VNO', 'Common', 'General', 'Annual', 8),
('Update VNO Registration Details', 'UL-VNO', 'Common', 'General', 'Annual', 5),
-- Financial
('Submit AGR Statement (VNO)', 'UL-VNO', 'Common', 'Financial', 'Quarterly', 9),
('Pay VNO License Fee', 'UL-VNO', 'Common', 'Financial', 'Quarterly', 10),
-- Technical
('Submit Network Usage Report', 'UL-VNO', 'Common', 'Technical', 'Monthly', 6),
('Maintain Service Level Agreements', 'UL-VNO', 'Common', 'Technical', 'Quarterly', 5),
-- Security
('Submit Security Compliance (VNO)', 'UL-VNO', 'Common', 'Security', 'Annual', 8),
('CAF Verification for VNO', 'UL-VNO', 'Common', 'Security', 'Monthly', 9),
-- Operating
('Submit Subscriber Report (VNO)', 'UL-VNO', 'Common', 'Operating', 'Monthly', 5),
('Maintain VNO Operations Log', 'UL-VNO', 'Common', 'Operating', 'Quarterly', 4);

-- Verify the data
SELECT condition_category, COUNT(*) as count FROM public.compliance_library GROUP BY condition_category;
